[build]
  command = "cd client && npm install && npm run build && cd ../netlify && npm install && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  # For local development, use the .env.development file instead of overriding VITE_API_BASE_URL here.
  # VITE_API_BASE_URL = "/api"
  # Set this to the local API URL for dev, or leave unset to use .env.development
  # VITE_API_BASE_URL = "http://localhost:8888"
  SESSION_SECRET = "" # Set this in Netlify UI, never commit secrets
  DATABASE_URL = "" # Set this in Netlify UI, never commit secrets

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[site]
  id = "069c9446-cee2-4862-acb3-716877b79f6b"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cookie, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Origin = "https://thebeauty.netlify.app"
    Access-Control-Expose-Headers = "Set-Cookie"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https://thebeauty.netlify.app; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://thebeauty.netlify.app"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
